//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.02 at 10:12:10 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gajewski.pl/SOAPws")
package pl.gajewski.SOAPws;
